[
  {
    "ProfileName": "Mulesoft Console Test",
    "Name": "",
    "Enabled": true,
    "Scanner": 1,
    "Author": "KingJulien",
    "Payloads": [
      "true,/console/",
      "true,/console/?amf",
      "true,/console/*/?amf"
    ],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [],
    "Tags": [
      "All",
      "API"
    ],
    "PayloadResponse": false,
    "NotResponse": false,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": false,
    "OnlyHTTP": false,
    "IsContentType": false,
    "ContentType": "",
    "HttpResponseCode": "200",
    "NegativeCT": false,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "isHeaderValue": false,
    "sequence": false,
    "NewHeaders": [],
    "MatchType": 9,
    "Scope": 0,
    "RedirType": 0,
    "MaxRedir": 0,
    "requestType": 1,
    "rawRequest": "",
    "payloadPosition": 1,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "Mulesoft Console Present",
    "IssueSeverity": "Low",
    "IssueConfidence": "Firm",
    "IssueDetail": "Mulesoft Console API Documentation available.",
    "RemediationDetail": "",
    "IssueBackground": "The disclosure of API documentation can significantly ease an attacker\u0027s effort in understanding the application\u0027s structure and functionality. This information can accelerate malicious efforts to exploit the API, leading to potential unauthorized access, data breaches, or other security incidents.",
    "RemediationBackground": "Consult Mulesoft documentation and disable or restrict access to the \"API Console\" in both UAT and PROD environments.\nIf the \"API Console\" is required, implement proper access controls to ensure only authorized personnel can access the API documentation.",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [
      66,
      65,
      33,
      37
    ],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false,
    "changeHttpRequest": false,
    "showIssue": false,
    "changeHttpRequestType": 1
  }
]