[
  {
    "ProfileName": "Possible Reflected XSS",
    "Name": "",
    "Enabled": true,
    "Scanner": 2,
    "Author": "@kingjulien",
    "Payloads": [],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [
      "true,,\u003clink rel\u003d\"canonical\" "
    ],
    "Tags": [
      "All",
      "XSS"
    ],
    "PayloadResponse": false,
    "NotResponse": false,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": true,
    "OnlyHTTP": false,
    "IsContentType": false,
    "ContentType": "",
    "HttpResponseCode": "",
    "NegativeCT": false,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "isHeaderValue": false,
    "sequence": false,
    "NewHeaders": [],
    "MatchType": 1,
    "Scope": 2,
    "RedirType": 0,
    "MaxRedir": 0,
    "requestType": 1,
    "rawRequest": "",
    "payloadPosition": 0,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "Possible XSS Canonical link tag injection",
    "IssueSeverity": "Low",
    "IssueConfidence": "Tentative",
    "IssueDetail": "Verify if you can control the href value for the identified \u003clink canonical tag.\u003cbr\u003e \u003cgrep\u003e\n",
    "RemediationDetail": "",
    "IssueBackground": "payload to try : ?%27accesskey\u003d%27x%27onclick\u003d%27alert(1)",
    "RemediationBackground": "",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false,
    "changeHttpRequest": false,
    "showIssue": false,
    "changeHttpRequestType": 0
  }
]