[
  {
    "ProfileName": "SecurityHeaders",
    "Name": "",
    "Enabled": true,
    "Scanner": 2,
    "Author": "@six2dez1",
    "Payloads": [],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [
      "true,,(?i)Cache-Control",
      "true,Or,(?i)X-Frame-Options",
      "true,Or,(?i)X-Content-Type-Options",
      "true,Or,(?i)Strict-Transport-Security",
      "true,Or,(?i)Content-Security-Policy"
    ],
    "Tags": [
      "All",
      "SecurityHeaders"
    ],
    "PayloadResponse": false,
    "NotResponse": true,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": false,
    "OnlyHTTP": true,
    "IsContentType": true,
    "ContentType": "text/css,image/jpeg,image/png,image/svg+xml,image/gif,image/tiff,image/webp,image/x-icon,application/font-woff,image/vnd.microsoft.icon,font/ttf,font/woff2,application/javascript,application/octet-stream",
    "HttpResponseCode": "",
    "NegativeCT": true,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "MatchType": 2,
    "Scope": 1,
    "RedirType": 0,
    "MaxRedir": 0,
    "payloadPosition": 0,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "Missing Security Headers",
    "IssueSeverity": "Low",
    "IssueConfidence": "Certain",
    "IssueDetail": "\"One or more security headers are missing. Please review the response headers.\"",
    "RemediationDetail": "",
    "IssueBackground": "",
    "RemediationBackground": "",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false
  }
]